/* soapAlertWebServiceSoapBindingProxy.h
   Generated by gSOAP 2.8.71 for AlertWebService.h

gSOAP XML Web services tools
Copyright (C) 2000-2018, Robert van Engelen, Genivia Inc. All Rights Reserved.
The soapcpp2 tool and its generated software are released under the GPL.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

#ifndef soapAlertWebServiceSoapBindingProxy_H
#define soapAlertWebServiceSoapBindingProxy_H
#include "soapH.h"

    class SOAP_CMAC AlertWebServiceSoapBindingProxy {
      public:
        /// Context to manage proxy IO and data
        struct soap *soap;
        /// flag indicating that this context is owned by this proxy and should be deleted by the destructor
        bool soap_own;
        /// Endpoint URL of service 'AlertWebServiceSoapBindingProxy' (change as needed)
        const char *soap_endpoint;
        /// Variables globally declared in AlertWebService.h, if any
        /// Construct a proxy with new managing context
        AlertWebServiceSoapBindingProxy();
        /// Copy constructor
        AlertWebServiceSoapBindingProxy(const AlertWebServiceSoapBindingProxy& rhs);
        /// Construct proxy given a shared managing context
        AlertWebServiceSoapBindingProxy(struct soap*);
        /// Construct proxy given a shared managing context and endpoint URL
        AlertWebServiceSoapBindingProxy(struct soap*, const char *endpoint);
        /// Constructor taking an endpoint URL
        AlertWebServiceSoapBindingProxy(const char *endpoint);
        /// Constructor taking input and output mode flags for the new managing context
        AlertWebServiceSoapBindingProxy(soap_mode iomode);
        /// Constructor taking endpoint URL and input and output mode flags for the new managing context
        AlertWebServiceSoapBindingProxy(const char *endpoint, soap_mode iomode);
        /// Constructor taking input and output mode flags for the new managing context
        AlertWebServiceSoapBindingProxy(soap_mode imode, soap_mode omode);
        /// Destructor deletes non-shared managing context only (use destroy() to delete deserialized data)
        virtual ~AlertWebServiceSoapBindingProxy();
        /// Initializer used by constructors
        virtual void AlertWebServiceSoapBindingProxy_init(soap_mode imode, soap_mode omode);
        /// Return a copy that has a new managing context with the same engine state
        virtual AlertWebServiceSoapBindingProxy *copy();
        /// Copy assignment
        AlertWebServiceSoapBindingProxy& operator=(const AlertWebServiceSoapBindingProxy&);
        /// Delete all deserialized data (uses soap_destroy() and soap_end())
        virtual void destroy();
        /// Delete all deserialized data and reset to default
        virtual void reset();
        /// Disables and removes SOAP Header from message by setting soap->header = NULL
        virtual void soap_noheader();
        /// Get SOAP Header structure (i.e. soap->header, which is NULL when absent)
        virtual ::SOAP_ENV__Header *soap_header();
        /// Get SOAP Fault structure (i.e. soap->fault, which is NULL when absent)
        virtual ::SOAP_ENV__Fault *soap_fault();
        /// Get SOAP Fault subcode QName string (NULL when absent)
        virtual const char *soap_fault_subcode();
        /// Get SOAP Fault string/reason (NULL when absent)
        virtual const char *soap_fault_string();
        /// Get SOAP Fault detail XML string (NULL when absent)
        virtual const char *soap_fault_detail();
        /// Close connection (normally automatic, except for send_X ops)
        virtual int soap_close_socket();
        /// Force close connection (can kill a thread blocked on IO)
        virtual int soap_force_close_socket();
        /// Print fault
        virtual void soap_print_fault(FILE*);
    #ifndef WITH_LEAN
    #ifndef WITH_COMPAT
        /// Print fault to stream
        virtual void soap_stream_fault(std::ostream&);
    #endif
        /// Write fault to buffer
        virtual char *soap_sprint_fault(char *buf, size_t len);
    #endif
        /// Web service operation 'GetVersion' (returns SOAP_OK or error code)
        virtual int GetVersion(std::string &GetVersionReturn)
        { return this->GetVersion(NULL, NULL, GetVersionReturn); }
        virtual int GetVersion(const char *soap_endpoint, const char *soap_action, std::string &GetVersionReturn);
        /// Web service operation 'ClearSystemAlert' (returns SOAP_OK or error code)
        virtual int ClearSystemAlert(int _in0, struct ns1__ClearSystemAlertResponse &_param_1)
        { return this->ClearSystemAlert(NULL, NULL, _in0, _param_1); }
        virtual int ClearSystemAlert(const char *soap_endpoint, const char *soap_action, int _in0, struct ns1__ClearSystemAlertResponse &_param_1);
        /// Web service operation 'ClearApplicationAlert' (returns SOAP_OK or error code)
        virtual int ClearApplicationAlert(int _in0, struct ns1__ClearApplicationAlertResponse &_param_1)
        { return this->ClearApplicationAlert(NULL, NULL, _in0, _param_1); }
        virtual int ClearApplicationAlert(const char *soap_endpoint, const char *soap_action, int _in0, struct ns1__ClearApplicationAlertResponse &_param_1);
        /// Web service operation 'GetSiteRecord' (returns SOAP_OK or error code)
        virtual int GetSiteRecord(std::string &GetSiteRecordReturn)
        { return this->GetSiteRecord(NULL, NULL, GetSiteRecordReturn); }
        virtual int GetSiteRecord(const char *soap_endpoint, const char *soap_action, std::string &GetSiteRecordReturn);
        /// Web service operation 'GetServerTypeRecord' (returns SOAP_OK or error code)
        virtual int GetServerTypeRecord(std::string &GetServerTypeRecordReturn)
        { return this->GetServerTypeRecord(NULL, NULL, GetServerTypeRecordReturn); }
        virtual int GetServerTypeRecord(const char *soap_endpoint, const char *soap_action, std::string &GetServerTypeRecordReturn);
        /// Web service operation 'GetServerRecord' (returns SOAP_OK or error code)
        virtual int GetServerRecord(std::string &GetServerRecordReturn)
        { return this->GetServerRecord(NULL, NULL, GetServerRecordReturn); }
        virtual int GetServerRecord(const char *soap_endpoint, const char *soap_action, std::string &GetServerRecordReturn);
        /// Web service operation 'GetTlkpSystemAlertStatesRecord' (returns SOAP_OK or error code)
        virtual int GetTlkpSystemAlertStatesRecord(std::string &GetTlkpSystemAlertStatesRecordReturn)
        { return this->GetTlkpSystemAlertStatesRecord(NULL, NULL, GetTlkpSystemAlertStatesRecordReturn); }
        virtual int GetTlkpSystemAlertStatesRecord(const char *soap_endpoint, const char *soap_action, std::string &GetTlkpSystemAlertStatesRecordReturn);
        /// Web service operation 'GetTlkpSystemAlertActionsRecord' (returns SOAP_OK or error code)
        virtual int GetTlkpSystemAlertActionsRecord(std::string &GetTlkpSystemAlertActionsRecordReturn)
        { return this->GetTlkpSystemAlertActionsRecord(NULL, NULL, GetTlkpSystemAlertActionsRecordReturn); }
        virtual int GetTlkpSystemAlertActionsRecord(const char *soap_endpoint, const char *soap_action, std::string &GetTlkpSystemAlertActionsRecordReturn);
        /// Web service operation 'GetTlkpSystemAlertTypesRecord' (returns SOAP_OK or error code)
        virtual int GetTlkpSystemAlertTypesRecord(std::string &GetTlkpSystemAlertTypesRecordReturn)
        { return this->GetTlkpSystemAlertTypesRecord(NULL, NULL, GetTlkpSystemAlertTypesRecordReturn); }
        virtual int GetTlkpSystemAlertTypesRecord(const char *soap_endpoint, const char *soap_action, std::string &GetTlkpSystemAlertTypesRecordReturn);
        /// Web service operation 'GetApplicationAlertsByStartDate' (returns SOAP_OK or error code)
        virtual int GetApplicationAlertsByStartDate(const std::string& _in0, const std::string& _in1, int _in2, std::string &_GetApplicationAlertsByStartDateReturn)
        { return this->GetApplicationAlertsByStartDate(NULL, NULL, _in0, _in1, _in2, _GetApplicationAlertsByStartDateReturn); }
        virtual int GetApplicationAlertsByStartDate(const char *soap_endpoint, const char *soap_action, const std::string& _in0, const std::string& _in1, int _in2, std::string &_GetApplicationAlertsByStartDateReturn);
        /// Web service operation 'GetApplicationAlerts' (returns SOAP_OK or error code)
        virtual int GetApplicationAlerts(const std::string& _in0, int _in1, std::string &_GetApplicationAlertsReturn)
        { return this->GetApplicationAlerts(NULL, NULL, _in0, _in1, _GetApplicationAlertsReturn); }
        virtual int GetApplicationAlerts(const char *soap_endpoint, const char *soap_action, const std::string& _in0, int _in1, std::string &_GetApplicationAlertsReturn);
        /// Web service operation 'GetApplicationAlertsFilter' (returns SOAP_OK or error code)
        virtual int GetApplicationAlertsFilter(const std::string& _in0, const std::string& _in1, const std::string& _in2, int _in3, int _in4, std::string &_GetApplicationAlertsFilterReturn)
        { return this->GetApplicationAlertsFilter(NULL, NULL, _in0, _in1, _in2, _in3, _in4, _GetApplicationAlertsFilterReturn); }
        virtual int GetApplicationAlertsFilter(const char *soap_endpoint, const char *soap_action, const std::string& _in0, const std::string& _in1, const std::string& _in2, int _in3, int _in4, std::string &_GetApplicationAlertsFilterReturn);
        /// Web service operation 'GetSystemAlertsFilter' (returns SOAP_OK or error code)
        virtual int GetSystemAlertsFilter(const std::string& _in0, const std::string& _in1, int _in2, int _in3, std::string &_GetSystemAlertsFilterReturn)
        { return this->GetSystemAlertsFilter(NULL, NULL, _in0, _in1, _in2, _in3, _GetSystemAlertsFilterReturn); }
        virtual int GetSystemAlertsFilter(const char *soap_endpoint, const char *soap_action, const std::string& _in0, const std::string& _in1, int _in2, int _in3, std::string &_GetSystemAlertsFilterReturn);
        /// Web service operation 'GetSystemAlertsByStartDate' (returns SOAP_OK or error code)
        virtual int GetSystemAlertsByStartDate(const std::string& _in0, int _in1, std::string &_GetSystemAlertsByStartDateReturn)
        { return this->GetSystemAlertsByStartDate(NULL, NULL, _in0, _in1, _GetSystemAlertsByStartDateReturn); }
        virtual int GetSystemAlertsByStartDate(const char *soap_endpoint, const char *soap_action, const std::string& _in0, int _in1, std::string &_GetSystemAlertsByStartDateReturn);
        /// Web service operation 'GetSystemAlerts' (returns SOAP_OK or error code)
        virtual int GetSystemAlerts(int _in0, std::string &_GetSystemAlertsReturn)
        { return this->GetSystemAlerts(NULL, NULL, _in0, _GetSystemAlertsReturn); }
        virtual int GetSystemAlerts(const char *soap_endpoint, const char *soap_action, int _in0, std::string &_GetSystemAlertsReturn);
        /// Web service operation 'AcknowledgeApplicationAlert' (returns SOAP_OK or error code)
        virtual int AcknowledgeApplicationAlert(int _in0, const std::string& _in1, struct ns1__AcknowledgeApplicationAlertResponse &_param_1)
        { return this->AcknowledgeApplicationAlert(NULL, NULL, _in0, _in1, _param_1); }
        virtual int AcknowledgeApplicationAlert(const char *soap_endpoint, const char *soap_action, int _in0, const std::string& _in1, struct ns1__AcknowledgeApplicationAlertResponse &_param_1);
        /// Web service operation 'AcknowledgeSystemAlert' (returns SOAP_OK or error code)
        virtual int AcknowledgeSystemAlert(int _in0, const std::string& _in1, struct ns1__AcknowledgeSystemAlertResponse &_param_1)
        { return this->AcknowledgeSystemAlert(NULL, NULL, _in0, _in1, _param_1); }
        virtual int AcknowledgeSystemAlert(const char *soap_endpoint, const char *soap_action, int _in0, const std::string& _in1, struct ns1__AcknowledgeSystemAlertResponse &_param_1);
        /// Web service operation 'DeleteAlertActionField2' (returns SOAP_OK or error code)
        virtual int DeleteAlertActionField2(int _in0, int _in1, struct ns1__DeleteAlertActionField2Response &_param_1)
        { return this->DeleteAlertActionField2(NULL, NULL, _in0, _in1, _param_1); }
        virtual int DeleteAlertActionField2(const char *soap_endpoint, const char *soap_action, int _in0, int _in1, struct ns1__DeleteAlertActionField2Response &_param_1);
        /// Web service operation 'DeleteAlertActionField' (returns SOAP_OK or error code)
        virtual int DeleteAlertActionField(int _in0, struct ns1__DeleteAlertActionFieldResponse &_param_1)
        { return this->DeleteAlertActionField(NULL, NULL, _in0, _param_1); }
        virtual int DeleteAlertActionField(const char *soap_endpoint, const char *soap_action, int _in0, struct ns1__DeleteAlertActionFieldResponse &_param_1);
        /// Web service operation 'DeleteAlertActionParameter2' (returns SOAP_OK or error code)
        virtual int DeleteAlertActionParameter2(int _in0, int _in1, struct ns1__DeleteAlertActionParameter2Response &_param_1)
        { return this->DeleteAlertActionParameter2(NULL, NULL, _in0, _in1, _param_1); }
        virtual int DeleteAlertActionParameter2(const char *soap_endpoint, const char *soap_action, int _in0, int _in1, struct ns1__DeleteAlertActionParameter2Response &_param_1);
        /// Web service operation 'DeleteAlertActionParameter' (returns SOAP_OK or error code)
        virtual int DeleteAlertActionParameter(int _in0, struct ns1__DeleteAlertActionParameterResponse &_param_1)
        { return this->DeleteAlertActionParameter(NULL, NULL, _in0, _param_1); }
        virtual int DeleteAlertActionParameter(const char *soap_endpoint, const char *soap_action, int _in0, struct ns1__DeleteAlertActionParameterResponse &_param_1);
        /// Web service operation 'DeleteAlertScheduleByScheduleId' (returns SOAP_OK or error code)
        virtual int DeleteAlertScheduleByScheduleId(int _in0, struct ns1__DeleteAlertScheduleByScheduleIdResponse &_param_1)
        { return this->DeleteAlertScheduleByScheduleId(NULL, NULL, _in0, _param_1); }
        virtual int DeleteAlertScheduleByScheduleId(const char *soap_endpoint, const char *soap_action, int _in0, struct ns1__DeleteAlertScheduleByScheduleIdResponse &_param_1);
        /// Web service operation 'DeleteAlertSchedule' (returns SOAP_OK or error code)
        virtual int DeleteAlertSchedule(int _in0, struct ns1__DeleteAlertScheduleResponse &_param_1)
        { return this->DeleteAlertSchedule(NULL, NULL, _in0, _param_1); }
        virtual int DeleteAlertSchedule(const char *soap_endpoint, const char *soap_action, int _in0, struct ns1__DeleteAlertScheduleResponse &_param_1);
        /// Web service operation 'DeleteAlertAction2' (returns SOAP_OK or error code)
        virtual int DeleteAlertAction2(int _in0, struct ns1__DeleteAlertAction2Response &_param_1)
        { return this->DeleteAlertAction2(NULL, NULL, _in0, _param_1); }
        virtual int DeleteAlertAction2(const char *soap_endpoint, const char *soap_action, int _in0, struct ns1__DeleteAlertAction2Response &_param_1);
        /// Web service operation 'DeleteAlertAction' (returns SOAP_OK or error code)
        virtual int DeleteAlertAction(int _in0, struct ns1__DeleteAlertActionResponse &_param_1)
        { return this->DeleteAlertAction(NULL, NULL, _in0, _param_1); }
        virtual int DeleteAlertAction(const char *soap_endpoint, const char *soap_action, int _in0, struct ns1__DeleteAlertActionResponse &_param_1);
        /// Web service operation 'DeleteAlertEvaluation2' (returns SOAP_OK or error code)
        virtual int DeleteAlertEvaluation2(int _in0, int _in1, struct ns1__DeleteAlertEvaluation2Response &_param_1)
        { return this->DeleteAlertEvaluation2(NULL, NULL, _in0, _in1, _param_1); }
        virtual int DeleteAlertEvaluation2(const char *soap_endpoint, const char *soap_action, int _in0, int _in1, struct ns1__DeleteAlertEvaluation2Response &_param_1);
        /// Web service operation 'DeleteAlertEvaluation' (returns SOAP_OK or error code)
        virtual int DeleteAlertEvaluation(int _in0, struct ns1__DeleteAlertEvaluationResponse &_param_1)
        { return this->DeleteAlertEvaluation(NULL, NULL, _in0, _param_1); }
        virtual int DeleteAlertEvaluation(const char *soap_endpoint, const char *soap_action, int _in0, struct ns1__DeleteAlertEvaluationResponse &_param_1);
        /// Web service operation 'DeleteAlert' (returns SOAP_OK or error code)
        virtual int DeleteAlert(int _in0, struct ns1__DeleteAlertResponse &_param_1)
        { return this->DeleteAlert(NULL, NULL, _in0, _param_1); }
        virtual int DeleteAlert(const char *soap_endpoint, const char *soap_action, int _in0, struct ns1__DeleteAlertResponse &_param_1);
        /// Web service operation 'GetRunningCenterCord' (returns SOAP_OK or error code)
        virtual int GetRunningCenterCord(struct ns1__GetRunningCenterCordResponse &_param_1)
        { return this->GetRunningCenterCord(NULL, NULL, _param_1); }
        virtual int GetRunningCenterCord(const char *soap_endpoint, const char *soap_action, struct ns1__GetRunningCenterCordResponse &_param_1);
        /// Web service operation 'SetClientType' (returns SOAP_OK or error code)
        virtual int SetClientType(int _in0, struct ns1__SetClientTypeResponse &_param_1)
        { return this->SetClientType(NULL, NULL, _in0, _param_1); }
        virtual int SetClientType(const char *soap_endpoint, const char *soap_action, int _in0, struct ns1__SetClientTypeResponse &_param_1);
        /// Web service operation 'SendServerUpdateNotification' (returns SOAP_OK or error code)
        virtual int SendServerUpdateNotification(const std::string& _in0, struct ns1__SendServerUpdateNotificationResponse &_param_1)
        { return this->SendServerUpdateNotification(NULL, NULL, _in0, _param_1); }
        virtual int SendServerUpdateNotification(const char *soap_endpoint, const char *soap_action, const std::string& _in0, struct ns1__SendServerUpdateNotificationResponse &_param_1);
        /// Web service operation 'UnSubscribeToDocumentType' (returns SOAP_OK or error code)
        virtual int UnSubscribeToDocumentType(int _in0, struct ns1__UnSubscribeToDocumentTypeResponse &_param_1)
        { return this->UnSubscribeToDocumentType(NULL, NULL, _in0, _param_1); }
        virtual int UnSubscribeToDocumentType(const char *soap_endpoint, const char *soap_action, int _in0, struct ns1__UnSubscribeToDocumentTypeResponse &_param_1);
        /// Web service operation 'SubscribeToDocumentType' (returns SOAP_OK or error code)
        virtual int SubscribeToDocumentType(int _in0, struct ns1__SubscribeToDocumentTypeResponse &_param_1)
        { return this->SubscribeToDocumentType(NULL, NULL, _in0, _param_1); }
        virtual int SubscribeToDocumentType(const char *soap_endpoint, const char *soap_action, int _in0, struct ns1__SubscribeToDocumentTypeResponse &_param_1);
        /// Web service operation 'SendNetworkDocument' (returns SOAP_OK or error code)
        virtual int SendNetworkDocument(const std::string& _in0, struct ns1__SendNetworkDocumentResponse &_param_1)
        { return this->SendNetworkDocument(NULL, NULL, _in0, _param_1); }
        virtual int SendNetworkDocument(const char *soap_endpoint, const char *soap_action, const std::string& _in0, struct ns1__SendNetworkDocumentResponse &_param_1);
        /// Web service operation 'SendAlert' (returns SOAP_OK or error code)
        virtual int SendAlert(int _in0, int _in1, int _in2, int _in3, int _in4, int _in5, const std::string& _in6, struct ns1__SendAlertResponse &_param_1)
        { return this->SendAlert(NULL, NULL, _in0, _in1, _in2, _in3, _in4, _in5, _in6, _param_1); }
        virtual int SendAlert(const char *soap_endpoint, const char *soap_action, int _in0, int _in1, int _in2, int _in3, int _in4, int _in5, const std::string& _in6, struct ns1__SendAlertResponse &_param_1);
        /// Web service operation 'GetTlkpActionParametersRecordByParameterId' (returns SOAP_OK or error code)
        virtual int GetTlkpActionParametersRecordByParameterId(int _in0, int _in1, std::string &_GetTlkpActionParametersRecordByParameterIdReturn)
        { return this->GetTlkpActionParametersRecordByParameterId(NULL, NULL, _in0, _in1, _GetTlkpActionParametersRecordByParameterIdReturn); }
        virtual int GetTlkpActionParametersRecordByParameterId(const char *soap_endpoint, const char *soap_action, int _in0, int _in1, std::string &_GetTlkpActionParametersRecordByParameterIdReturn);
        /// Web service operation 'GetTlkpActionParametersRecord' (returns SOAP_OK or error code)
        virtual int GetTlkpActionParametersRecord(int _in0, std::string &_GetTlkpActionParametersRecordReturn)
        { return this->GetTlkpActionParametersRecord(NULL, NULL, _in0, _GetTlkpActionParametersRecordReturn); }
        virtual int GetTlkpActionParametersRecord(const char *soap_endpoint, const char *soap_action, int _in0, std::string &_GetTlkpActionParametersRecordReturn);
        /// Web service operation 'GetTlkpPriorityLevelRecordByPriorityLevel' (returns SOAP_OK or error code)
        virtual int GetTlkpPriorityLevelRecordByPriorityLevel(int _in0, std::string &_GetTlkpPriorityLevelRecordByPriorityLevelReturn)
        { return this->GetTlkpPriorityLevelRecordByPriorityLevel(NULL, NULL, _in0, _GetTlkpPriorityLevelRecordByPriorityLevelReturn); }
        virtual int GetTlkpPriorityLevelRecordByPriorityLevel(const char *soap_endpoint, const char *soap_action, int _in0, std::string &_GetTlkpPriorityLevelRecordByPriorityLevelReturn);
        /// Web service operation 'GetTlkpPriorityLevelRecord' (returns SOAP_OK or error code)
        virtual int GetTlkpPriorityLevelRecord(std::string &GetTlkpPriorityLevelRecordReturn)
        { return this->GetTlkpPriorityLevelRecord(NULL, NULL, GetTlkpPriorityLevelRecordReturn); }
        virtual int GetTlkpPriorityLevelRecord(const char *soap_endpoint, const char *soap_action, std::string &GetTlkpPriorityLevelRecordReturn);
        /// Web service operation 'GetTlkpActionsRecordByAction' (returns SOAP_OK or error code)
        virtual int GetTlkpActionsRecordByAction(int _in0, std::string &_GetTlkpActionsRecordByActionReturn)
        { return this->GetTlkpActionsRecordByAction(NULL, NULL, _in0, _GetTlkpActionsRecordByActionReturn); }
        virtual int GetTlkpActionsRecordByAction(const char *soap_endpoint, const char *soap_action, int _in0, std::string &_GetTlkpActionsRecordByActionReturn);
        /// Web service operation 'GetTlkpActionsRecord' (returns SOAP_OK or error code)
        virtual int GetTlkpActionsRecord(std::string &GetTlkpActionsRecordReturn)
        { return this->GetTlkpActionsRecord(NULL, NULL, GetTlkpActionsRecordReturn); }
        virtual int GetTlkpActionsRecord(const char *soap_endpoint, const char *soap_action, std::string &GetTlkpActionsRecordReturn);
        /// Web service operation 'GetTlkpDocumentFieldTypesRecord' (returns SOAP_OK or error code)
        virtual int GetTlkpDocumentFieldTypesRecord(int _in0, std::string &_GetTlkpDocumentFieldTypesRecordReturn)
        { return this->GetTlkpDocumentFieldTypesRecord(NULL, NULL, _in0, _GetTlkpDocumentFieldTypesRecordReturn); }
        virtual int GetTlkpDocumentFieldTypesRecord(const char *soap_endpoint, const char *soap_action, int _in0, std::string &_GetTlkpDocumentFieldTypesRecordReturn);
        /// Web service operation 'GetTlkpDocumentFieldsRecord' (returns SOAP_OK or error code)
        virtual int GetTlkpDocumentFieldsRecord(int _in0, std::string &_GetTlkpDocumentFieldsRecordReturn)
        { return this->GetTlkpDocumentFieldsRecord(NULL, NULL, _in0, _GetTlkpDocumentFieldsRecordReturn); }
        virtual int GetTlkpDocumentFieldsRecord(const char *soap_endpoint, const char *soap_action, int _in0, std::string &_GetTlkpDocumentFieldsRecordReturn);
        /// Web service operation 'GetTlkpDocumentTypesRecordByClientType' (returns SOAP_OK or error code)
        virtual int GetTlkpDocumentTypesRecordByClientType(int _in0, std::string &_GetTlkpDocumentTypesRecordByClientTypeReturn)
        { return this->GetTlkpDocumentTypesRecordByClientType(NULL, NULL, _in0, _GetTlkpDocumentTypesRecordByClientTypeReturn); }
        virtual int GetTlkpDocumentTypesRecordByClientType(const char *soap_endpoint, const char *soap_action, int _in0, std::string &_GetTlkpDocumentTypesRecordByClientTypeReturn);
        /// Web service operation 'GetTlkpDocumentTypesRecord' (returns SOAP_OK or error code)
        virtual int GetTlkpDocumentTypesRecord(std::string &GetTlkpDocumentTypesRecordReturn)
        { return this->GetTlkpDocumentTypesRecord(NULL, NULL, GetTlkpDocumentTypesRecordReturn); }
        virtual int GetTlkpDocumentTypesRecord(const char *soap_endpoint, const char *soap_action, std::string &GetTlkpDocumentTypesRecordReturn);
        /// Web service operation 'GetAlertActionFieldsRecord' (returns SOAP_OK or error code)
        virtual int GetAlertActionFieldsRecord(int _in0, std::string &_GetAlertActionFieldsRecordReturn)
        { return this->GetAlertActionFieldsRecord(NULL, NULL, _in0, _GetAlertActionFieldsRecordReturn); }
        virtual int GetAlertActionFieldsRecord(const char *soap_endpoint, const char *soap_action, int _in0, std::string &_GetAlertActionFieldsRecordReturn);
        /// Web service operation 'GetAlertActionParameterRecord' (returns SOAP_OK or error code)
        virtual int GetAlertActionParameterRecord(int _in0, std::string &_GetAlertActionParameterRecordReturn)
        { return this->GetAlertActionParameterRecord(NULL, NULL, _in0, _GetAlertActionParameterRecordReturn); }
        virtual int GetAlertActionParameterRecord(const char *soap_endpoint, const char *soap_action, int _in0, std::string &_GetAlertActionParameterRecordReturn);
        /// Web service operation 'GetAlertSchedulesRecord' (returns SOAP_OK or error code)
        virtual int GetAlertSchedulesRecord(int _in0, std::string &_GetAlertSchedulesRecordReturn)
        { return this->GetAlertSchedulesRecord(NULL, NULL, _in0, _GetAlertSchedulesRecordReturn); }
        virtual int GetAlertSchedulesRecord(const char *soap_endpoint, const char *soap_action, int _in0, std::string &_GetAlertSchedulesRecordReturn);
        /// Web service operation 'GetAlertActionsRecord' (returns SOAP_OK or error code)
        virtual int GetAlertActionsRecord(int _in0, std::string &_GetAlertActionsRecordReturn)
        { return this->GetAlertActionsRecord(NULL, NULL, _in0, _GetAlertActionsRecordReturn); }
        virtual int GetAlertActionsRecord(const char *soap_endpoint, const char *soap_action, int _in0, std::string &_GetAlertActionsRecordReturn);
        /// Web service operation 'GetAlertEvaluationsRecord' (returns SOAP_OK or error code)
        virtual int GetAlertEvaluationsRecord(int _in0, std::string &_GetAlertEvaluationsRecordReturn)
        { return this->GetAlertEvaluationsRecord(NULL, NULL, _in0, _GetAlertEvaluationsRecordReturn); }
        virtual int GetAlertEvaluationsRecord(const char *soap_endpoint, const char *soap_action, int _in0, std::string &_GetAlertEvaluationsRecordReturn);
        /// Web service operation 'GetAlertsRecordByDocumentType' (returns SOAP_OK or error code)
        virtual int GetAlertsRecordByDocumentType(int _in0, std::string &_GetAlertsRecordByDocumentTypeReturn)
        { return this->GetAlertsRecordByDocumentType(NULL, NULL, _in0, _GetAlertsRecordByDocumentTypeReturn); }
        virtual int GetAlertsRecordByDocumentType(const char *soap_endpoint, const char *soap_action, int _in0, std::string &_GetAlertsRecordByDocumentTypeReturn);
        /// Web service operation 'GetAlertsRecord' (returns SOAP_OK or error code)
        virtual int GetAlertsRecord(std::string &GetAlertsRecordReturn)
        { return this->GetAlertsRecord(NULL, NULL, GetAlertsRecordReturn); }
        virtual int GetAlertsRecord(const char *soap_endpoint, const char *soap_action, std::string &GetAlertsRecordReturn);
        /// Web service operation 'UpdateAlertActionField' (returns SOAP_OK or error code)
        virtual int UpdateAlertActionField(int _in0, int _in1, struct ns1__UpdateAlertActionFieldResponse &_param_1)
        { return this->UpdateAlertActionField(NULL, NULL, _in0, _in1, _param_1); }
        virtual int UpdateAlertActionField(const char *soap_endpoint, const char *soap_action, int _in0, int _in1, struct ns1__UpdateAlertActionFieldResponse &_param_1);
        /// Web service operation 'InsertAlertActionField' (returns SOAP_OK or error code)
        virtual int InsertAlertActionField(int _in0, int _in1, struct ns1__InsertAlertActionFieldResponse &_param_1)
        { return this->InsertAlertActionField(NULL, NULL, _in0, _in1, _param_1); }
        virtual int InsertAlertActionField(const char *soap_endpoint, const char *soap_action, int _in0, int _in1, struct ns1__InsertAlertActionFieldResponse &_param_1);
        /// Web service operation 'UpdateAlertActionParameter' (returns SOAP_OK or error code)
        virtual int UpdateAlertActionParameter(int _in0, int _in1, const std::string& _in2, struct ns1__UpdateAlertActionParameterResponse &_param_1)
        { return this->UpdateAlertActionParameter(NULL, NULL, _in0, _in1, _in2, _param_1); }
        virtual int UpdateAlertActionParameter(const char *soap_endpoint, const char *soap_action, int _in0, int _in1, const std::string& _in2, struct ns1__UpdateAlertActionParameterResponse &_param_1);
        /// Web service operation 'InsertAlertActionParameter' (returns SOAP_OK or error code)
        virtual int InsertAlertActionParameter(int _in0, int _in1, const std::string& _in2, struct ns1__InsertAlertActionParameterResponse &_param_1)
        { return this->InsertAlertActionParameter(NULL, NULL, _in0, _in1, _in2, _param_1); }
        virtual int InsertAlertActionParameter(const char *soap_endpoint, const char *soap_action, int _in0, int _in1, const std::string& _in2, struct ns1__InsertAlertActionParameterResponse &_param_1);
        /// Web service operation 'UpdateAlertSchedule' (returns SOAP_OK or error code)
        virtual int UpdateAlertSchedule(int _in0, const std::string& _in1, const std::string& _in2, const std::string& _in3, const std::string& _in4, const std::string& _in5, struct ns1__UpdateAlertScheduleResponse &_param_1)
        { return this->UpdateAlertSchedule(NULL, NULL, _in0, _in1, _in2, _in3, _in4, _in5, _param_1); }
        virtual int UpdateAlertSchedule(const char *soap_endpoint, const char *soap_action, int _in0, const std::string& _in1, const std::string& _in2, const std::string& _in3, const std::string& _in4, const std::string& _in5, struct ns1__UpdateAlertScheduleResponse &_param_1);
        /// Web service operation 'InsertAlertSchedule' (returns SOAP_OK or error code)
        virtual int InsertAlertSchedule(int _in0, const std::string& _in1, const std::string& _in2, const std::string& _in3, const std::string& _in4, const std::string& _in5, int &_InsertAlertScheduleReturn)
        { return this->InsertAlertSchedule(NULL, NULL, _in0, _in1, _in2, _in3, _in4, _in5, _InsertAlertScheduleReturn); }
        virtual int InsertAlertSchedule(const char *soap_endpoint, const char *soap_action, int _in0, const std::string& _in1, const std::string& _in2, const std::string& _in3, const std::string& _in4, const std::string& _in5, int &_InsertAlertScheduleReturn);
        /// Web service operation 'UpdateAlertAction' (returns SOAP_OK or error code)
        virtual int UpdateAlertAction(int _in0, int _in1, struct ns1__UpdateAlertActionResponse &_param_1)
        { return this->UpdateAlertAction(NULL, NULL, _in0, _in1, _param_1); }
        virtual int UpdateAlertAction(const char *soap_endpoint, const char *soap_action, int _in0, int _in1, struct ns1__UpdateAlertActionResponse &_param_1);
        /// Web service operation 'InsertAlertAction' (returns SOAP_OK or error code)
        virtual int InsertAlertAction(int _in0, int _in1, int _in2, int &_InsertAlertActionReturn)
        { return this->InsertAlertAction(NULL, NULL, _in0, _in1, _in2, _InsertAlertActionReturn); }
        virtual int InsertAlertAction(const char *soap_endpoint, const char *soap_action, int _in0, int _in1, int _in2, int &_InsertAlertActionReturn);
        /// Web service operation 'UpdatetAlertEvaluation' (returns SOAP_OK or error code)
        virtual int UpdatetAlertEvaluation(int _in0, const std::string& _in1, struct ns1__UpdatetAlertEvaluationResponse &_param_1)
        { return this->UpdatetAlertEvaluation(NULL, NULL, _in0, _in1, _param_1); }
        virtual int UpdatetAlertEvaluation(const char *soap_endpoint, const char *soap_action, int _in0, const std::string& _in1, struct ns1__UpdatetAlertEvaluationResponse &_param_1);
        /// Web service operation 'InsertAlertEvaluation' (returns SOAP_OK or error code)
        virtual int InsertAlertEvaluation(int _in0, const std::string& _in1, int &_InsertAlertEvaluationReturn)
        { return this->InsertAlertEvaluation(NULL, NULL, _in0, _in1, _InsertAlertEvaluationReturn); }
        virtual int InsertAlertEvaluation(const char *soap_endpoint, const char *soap_action, int _in0, const std::string& _in1, int &_InsertAlertEvaluationReturn);
        /// Web service operation 'UpdateAlert' (returns SOAP_OK or error code)
        virtual int UpdateAlert(int _in0, const std::string& _in1, const std::string& _in2, int _in3, int _in4, struct ns1__UpdateAlertResponse &_param_1)
        { return this->UpdateAlert(NULL, NULL, _in0, _in1, _in2, _in3, _in4, _param_1); }
        virtual int UpdateAlert(const char *soap_endpoint, const char *soap_action, int _in0, const std::string& _in1, const std::string& _in2, int _in3, int _in4, struct ns1__UpdateAlertResponse &_param_1);
        /// Web service operation 'InsertAlert' (returns SOAP_OK or error code)
        virtual int InsertAlert(int _in0, const std::string& _in1, const std::string& _in2, int _in3, const std::string& _in4, int _in5, int &_InsertAlertReturn)
        { return this->InsertAlert(NULL, NULL, _in0, _in1, _in2, _in3, _in4, _in5, _InsertAlertReturn); }
        virtual int InsertAlert(const char *soap_endpoint, const char *soap_action, int _in0, const std::string& _in1, const std::string& _in2, int _in3, const std::string& _in4, int _in5, int &_InsertAlertReturn);
        /// Web service operation 'GetWebServiceName' (returns SOAP_OK or error code)
        virtual int GetWebServiceName(std::string &GetWebServiceNameReturn)
        { return this->GetWebServiceName(NULL, NULL, GetWebServiceNameReturn); }
        virtual int GetWebServiceName(const char *soap_endpoint, const char *soap_action, std::string &GetWebServiceNameReturn);
    };
#endif
